### ISSUE TITLE
不显示位置和国旗

### ISSUE THREAD

**Issue by catxian** [k0baya/nezha4serv00#2]
没事，不修也没事的，我手动写地区。。。

**Comment by k0baya** [comment]
参考：https://nezha.wiki/guide/q11.html
这个不是脚本问题，是二进制文件在构建的时候没有正确设置离线数据库导致的。

本仓库使用的二进制文件来自：https://github.com/wansyu/nezha-freebsd

这个问题不该在这里提，该去提供二进制文件的仓库提。

**Comment by catxian** [comment]
好滴
