### ISSUE TITLE
如何保活啊？

### ISSUE THREAD

**Issue by zyhiderole** [k0baya/nezha4serv00#4]
装完 两天就自动掉了,怎么保活啊 大佬 能配合xforsev00 一起吗？

**Comment by k0baya** [comment]
请参考这个链接：[Serv00 进程保活最终解决方案](https://saika.us.kg/2024/08/15/serv00-keep-alive/)
本仓库不再赘述保活相关事项。
能配合`x-for-serv00`一起，需要在`app.js`中加入相关的保活部分。
