### ISSUE TITLE
使用哪吒监控v1，脚本失效

### ISSUE THREAD

**Issue by LFMJUN** [k0baya/nezha4serv00#6]
![image](https://github.com/user-attachments/assets/5fa8e466-8e93-47bb-9911-c719caaf5e4b)
![image](https://github.com/user-attachments/assets/62666f43-4be0-4532-8199-9466198a9c33)
如图

**Comment by LFMJUN** [comment]
p1站点地址填写的是服务器的ip地址

**Comment by LFMJUN** [comment]
发现问题为哪吒更换了配置传参，使用config为程序配置文件，导致strat.sh无法执行

**Comment by k0baya** [comment]
好的，感谢提醒，有空会更新适配最新版本的变化。

**Comment by LFMJUN** [comment]
#7
